
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: alastria.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # CoreADM
  # ---------------------------------------------------------------------------
  - Name: coreAdm
    Domain: coreAdm.alastria.com
    Template:
      Count: 1 #Number of peers
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # ORG1
  # ---------------------------------------------------------------------------
  - Name: org1
    Domain: org1.alastria.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # ORG2
  # ---------------------------------------------------------------------------
  - Name: org2
    Domain: org2.alastria.com
    Template:
      Count: 1
    Users:
      Count: 1

