# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.alastria.com:
    container_name: orderer.alastria.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/alastria.com/orderers/orderer.alastria.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/alastria.com/orderers/orderer.alastria.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.coreAdm.alastria.com:
   container_name: peer0.coreAdm.alastria.com
   extends:
    file: peer-base.yaml
    service: peer-base
   environment:
     - CORE_PEER_ID=peer0.coreAdm.alastria.com
     - CORE_PEER_ADDRESS=peer0.coreAdm.alastria.com:7051
     - CORE_PEER_CHAINCODELISTENADDRESS=peer0.coreAdm.alastria.com:7052
     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coreAdm.alastria.com:7051
     - CORE_PEER_LOCALMSPID=coreAdmMSP
   volumes:
       - /var/run/:/host/var/run/
       - ../crypto-config/peerOrganizations/coreAdm.alastria.com/peers/peer0.coreAdm.alastria.com/msp:/etc/hyperledger/fabric/msp
       - ../crypto-config/peerOrganizations/coreAdm.alastria.com/peers/peer0.coreAdm.alastria.com/tls:/etc/hyperledger/fabric/tls
   ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer0.org1.alastria.com:
    container_name: peer0.org1.alastria.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.alastria.com
      - CORE_PEER_ADDRESS=peer0.org1.alastria.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.alastria.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.alastria.com:7051
      - CORE_PEER_LOCALMSPID=org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.alastria.com/peers/peer0.org1.alastria.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.alastria.com/peers/peer0.org1.alastria.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053



  peer0.org2.alastria.com:
    container_name: peer0.org2.alastria.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.alastria.com
      - CORE_PEER_ADDRESS=peer0.org2.alastria.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.alastria.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.alastria.com:7051
      - CORE_PEER_LOCALMSPID=org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.alastria.com/peers/peer0.org2.alastria.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.alastria.com/peers/peer0.org2.alastria.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053