version: '2'

services:
  caCoreAdm:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coreAdm
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.coreAdm.alastria.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2a5d9fda22ea8423d73568178f2be2ead41950e692f39299e80738e68a923a13_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.coreAdm.alastria.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2a5d9fda22ea8423d73568178f2be2ead41950e692f39299e80738e68a923a13_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/coreAdm.alastria.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCoreAdm
  
  caOrg1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.alastria.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/cd4e3b54fe04a07d8269db8ee11664bd6e1672fa9af2ca20b639cfa60b48c4b5_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.alastria.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/cd4e3b54fe04a07d8269db8ee11664bd6e1672fa9af2ca20b639cfa60b48c4b5_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.alastria.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.alastria.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8e789527ea6dda4853145914c2195eef19f97624aa874e6ac4ead566c3f3fa60_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.alastria.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8e789527ea6dda4853145914c2195eef19f97624aa874e6ac4ead566c3f3fa60_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.alastria.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2

  orderer.alastria.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.alastria.com
    container_name: orderer.alastria.com

  peer0.coreAdm.alastria.com:
    container_name: peer0.coreAdm.alastria.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.coreAdm.alastria.com

  peer0.org1.alastria.com:
    container_name: peer0.org1.alastria.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.alastria.com

  peer0.org2.alastria.com:
    container_name: peer0.org2.alastria.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.alastria.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.coreAdm.alastria.com:7051
      - CORE_PEER_LOCALMSPID=coreAdmMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/coreAdm.alastria.com/peers/peer0.coreAdm.alastria.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/coreAdm.alastria.com/peers/peer0.coreAdm.alastria.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/coreAdm.alastria.com/peers/peer0.coreAdm.alastria.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/coreAdm.alastria.com/users/Admin@coreAdm.alastria.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/configure.sh; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hlf-go/example-chaincodes/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.alastria.com
      - peer0.coreAdm.alastria.com
      - peer0.org1.alastria.com
      - peer0.org2.alastria.com